### ISSUE TITLE
Check how point mutations or genes with a period are treated

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#269] opened 2023-02-28 15:12 UTC

**Comment by hfuchs5** [comment] 2023-03-14 13:08
I did this in my project with TERT.5flank and it worked fine with the annotations and `create_binary_matrix`

**Comment by hfuchs5** [comment] 2023-04-11 14:14
add warning to say that any non-impact named genes then they won't be NA annotated

add test to make sure these columns are working properly

**Comment by hfuchs5** [comment] 2023-04-11 14:16
check warnings with NA annotate and removing the all NA columns

**Comment by hfuchs5** [comment] 2023-04-19 18:14
NOTE: these genes will be annotated with NA if a gene-panel is specified. People will have to make a separate gene_binary matrix and then cbind/left_join to the rest. 

Also, if a period is in the column name, there is some issue including the variable in a logistic regression model formula. Will have to rename to make it work, but this is not an issue we plan to address because it can be fixed with tidyverse.

**Closed as completed** 2023-04-19 18:14 UTC
Labels: hackathon
